name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron:  '37 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Update README
      run: ruby ./parse.rb
    - name: Commit and push if README changed
      run: |-
        git diff
        git config user.name "Ruby script"
        git config user.email "ruby@users.noreply.github.com"
        git add -A
        git commit -m "Update README" || exit 0
        git push
